export const quiz = {
  totalQuestions: 5,
  questions: [
    {
      id: 1,
      question: 'Who is the current President of the United States?',
      answers: ['Joe Biden', 'Donald Trump', 'Barack Obama', 'George W. Bush'],
      correctAnswer: 'Joe Biden',
    },
    {
      id: 2,
      question: 'What is the largest ocean on Earth?',
      answers: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
      correctAnswer: 'Pacific Ocean',
    },
    {
      id: 3,
      question: 'Which country is known as the Land of the Rising Sun?',
      answers: ['China', 'Japan', 'Korea', 'Thailand'],
      correctAnswer: 'Japan',
    },
    {
      id: 4,
      question: 'Who painted the famous artwork "The Starry Night"?',
      answers: ['Pablo Picasso', 'Claude Monet', 'Vincent van Gogh', 'Salvador Dali'],
      correctAnswer: 'Vincent van Gogh',
    },
    {
      id: 5,
      question: 'What is the capital city of Australia?',
      answers: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
      correctAnswer: 'Canberra',
    },
    // {
    //   id: 6,
    //   question: 'Who developed the theory of general relativity?',
    //   answers: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Stephen Hawking'],
    //   correctAnswer: 'Albert Einstein',
    // },
    // {
    //   id: 7,
    //   question: 'Which is the largest country by land area?',
    //   answers: ['Russia', 'Canada', 'China', 'United States'],
    //   correctAnswer: 'Russia',
    // },
    // {
    //   id: 8,
    //   question: 'Who wrote the novel "To Kill a Mockingbird"?',
    //   answers: ['Harper Lee', 'F. Scott Fitzgerald', 'Mark Twain', 'Ernest Hemingway'],
    //   correctAnswer: 'Harper Lee',
    // },
    // {
    //   id: 9,
    //   question: 'What is the capital city of Brazil?',
    //   answers: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'],
    //   correctAnswer: 'Brasília',
    // },
    // {
    //   id: 10,
    //   question: 'Who invented the telephone?',
    //   answers: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Albert Einstein'],
    //   correctAnswer: 'Alexander Graham Bell',
    // },
    // {
    //   id: 11,
    //   question: 'Which city is known as the Big Apple?',
    //   answers: ['Chicago', 'New York City', 'Los Angeles', 'Houston'],
    //   correctAnswer: 'New York City',
    // },
    // {
    //   id: 12,
    //   question: 'What is the chemical symbol for Gold?',
    //   answers: ['Ag', 'Au', 'Gd', 'Go'],
    //   correctAnswer: 'Au',
    // },
    // {
    //   id: 13,
    //   question: 'Who painted the famous artwork "The Last Supper"?',
    //   answers: ['Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet', 'Vincent van Gogh'],
    //   correctAnswer: 'Leonardo da Vinci',
    // },
    // {
    //   id: 14,
    //   question: 'What is the currency of Switzerland?',
    //   answers: ['Euro', 'Pound', 'Dollar', 'Swiss Franc'],
    //   correctAnswer: 'Swiss Franc',
    // },
    // {
    //   id: 15,
    //   question: 'Who is the author of the Harry Potter book series?',
    //   answers: ['J.K. Rowling', 'Stephen King', 'George R.R. Martin', 'Dan Brown'],
    //   correctAnswer: 'J.K. Rowling',
    // },
    // {
    //   id: 16,
    //   question: 'What is the tallest mountain in the world?',
    //   answers: ['Mount Everest', 'K2', 'Kangchenjunga', 'Makalu'],
    //   correctAnswer: 'Mount Everest',
    // },
    // {
    //   id: 17,
    //   question: 'What is the official language of China?',
    //   answers: ['English', 'Spanish', 'Chinese', 'Mandarin'],
    //   correctAnswer: 'Chinese',
    // },
    // {
    //   id: 18,
    //   question: 'Which planet is known as the Red Planet?',
    //   answers: ['Mars', 'Jupiter', 'Venus', 'Saturn'],
    //   correctAnswer: 'Mars',
    // },
    // {
    //   id: 19,
    //   question: 'Who is the CEO of Tesla?',
    //   answers: ['Jeff Bezos', 'Elon Musk', 'Tim Cook', 'Satya Nadella'],
    //   correctAnswer: 'Elon Musk',
    // },
    // {
    //   id: 20,
    //   question: 'Which country won the FIFA World Cup in 2018?',
    //   answers: ['Brazil', 'Germany', 'France', 'Spain'],
    //   correctAnswer: 'France',
    // },
  ],
};
